"""made posts id as the string and removed slug as the identifier

Revision ID: 23a23a35838f
Revises: cd50b3eded55
Create Date: 2026-04-17 07:56:43.698069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a23a35838f'
down_revision: Union[str, Sequence[str], None] = 'cd50b3eded55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_posts_slug'), table_name='posts')
    op.create_unique_constraint(None, 'posts', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.create_index(op.f('ix_posts_slug'), 'posts', ['slug'], unique=True)
    op.alter_column('posts', 'id',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
