"""add foreign key constraint for the user's profile image

Revision ID: ca2c5740e17e
Revises: a589f4d1e448
Create Date: 2026-02-11 04:03:45.554640

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca2c5740e17e"
down_revision: Union[str, Sequence[str], None] = "a589f4d1e448"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_user_profile_image",
        "users",
        "media",
        ["profile_image_id"],
        ["id"],
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_user_profile_image", "users", type_="foreignkey")
    # ### end Alembic commands ###
