"""added post featured image foreign key mapping to media

Revision ID: cd50b3eded55
Revises: ca2c5740e17e
Create Date: 2026-02-11 04:18:09.417959

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd50b3eded55"
down_revision: Union[str, Sequence[str], None] = "ca2c5740e17e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("featured_image_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_post_featured_image",
        "posts",
        "media",
        ["featured_image_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("posts", "featured_image")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column("featured_image", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint("fk_post_featured_image", "posts", type_="foreignkey")
    op.drop_column("posts", "featured_image_id")
    # ### end Alembic commands ###
