"""added media usage table to track the media files being used

Revision ID: fbaaf637d182
Revises: 23a23a35838f
Create Date: 2026-04-23 11:38:39.995146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbaaf637d182'
down_revision: Union[str, Sequence[str], None] = '23a23a35838f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('block_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entity_lookup', 'media_usage', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_media_usage_media_id'), 'media_usage', ['media_id'], unique=False)
    op.create_index('uq_media_usage_block', 'media_usage', ['media_id', 'entity_type', 'entity_id', 'block_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_media_usage_block', table_name='media_usage')
    op.drop_index(op.f('ix_media_usage_media_id'), table_name='media_usage')
    op.drop_index('idx_entity_lookup', table_name='media_usage')
    op.drop_table('media_usage')
    # ### end Alembic commands ###
